### ISSUE TITLE
Unable to claim gas

### ISSUE THREAD

**Issue by mike15623** [CityOfZion/OzoneWalletIOS#22]
I’ve got a couple NEO in O3, and I have been able to claim the GAS in the past, but no longer (they are still accruing).

When I click the Claim button, it doesn’t fade out and stay that way, it just does a quick flash to faded and returns.

iPhone 6s, latest iOS.  Restarted app and phone many times, issue has persisted for a few days now.

**Comment by saltyskip** [comment]
Hi Mike we've figured out this issue, I believe its affecting NEON wallet as well. 

Currently our best node API is hitting this one  
http://seed3.neo.org:10332

However you can see here that the node is far behind the others http://monitor.cityofzion.io/

We will improve network management in the next build so that even if the default node goes down you can manually select one that works.

**Comment by mike15623** [comment]
Well shoots, restart that bad boy!

Glad you figured it out, hope the fix is an easy one.

-mike

**Comment by canesin** [comment]
You could filter nodes using:
https://neoscan.io//api/main_net/v1/get_nodes
Them from these select best node for you.

**Comment by dkliman** [comment]
Can't the app go looking for working nodes itself?

**Comment by saltyskip** [comment]
Yes it could, but our current solution will be to only use manual node selection, with a static default. We were previously using the CoZ API to get the best node, but since we can't guarantee the uptime of that API, manual selection will be the best short term solution

**Comment by Govertillo2** [comment]
Somebody sent me by mistake Gas to my neo account which does not have Gad available. How can I use this gas?

**Comment by saltyskip** [comment]
I'm not sure I understand. Could you clarify the situation.

**Comment by Govertillo2** [comment]
I have an account in coinpayments. I wanted to receive neo there but the person who was gonna send me the neo also send me some gas to the same address. However, in coinpayments there is no option for Gas, just for Neo. My question is how can I use that gas. If I check in neoexplorer the gas is there. But there is not option in coinpayments tu use it.
