### ISSUE TITLE
Make the dot on Numeric Keyboard always be a dot

### ISSUE THREAD

**Issue by saltyskip** [CityOfZion/OzoneWalletIOS#48]
On some keyboard locales the dot defaults to a comma. It should always be a dot to allow for fractional sending

**Comment by apisit** [comment]
#52 
we cannot force the keyboard to show dot for decimal. it's from phone's set locale.
Updated it to parse the amount for NumberFormatter. Tested.
![simulator screen shot - iphone 8 - 2018-01-23 at 11 57 07](https://user-images.githubusercontent.com/1012916/35255906-a372ac6a-0034-11e8-86e5-38bcbc242660.png)
![simulator screen shot - iphone 8 - 2018-01-23 at 11 57 04](https://user-images.githubusercontent.com/1012916/35255907-a39b34d2-0034-11e8-8ccb-fd6422794de6.png)

**Comment by apisit** [comment]
fixed.
